### ISSUE TITLE
gustav-(Gustavo-Blanco)-Contributor-License-Agreement.md

### ISSUE THREAD

**Issue by Chofo7** [Fermat-ORG/contribution-program#17]

**Comment by gustl-arg** [comment]
@Chofo7 no se como creaste un ISSUE en lugar de crear un archivo (new file) y hacer un Pull request.
Por favor, reintenta siguiendo los pasos en : https://github.com/bitdubai/contribution-program/tree/master/license-agreements/README.md

pongo en copia a @rjgroenke manager de la competencia (skype: romulo.groenke1) para que te asista.

**Comment by gustl-arg** [comment]
user quitted the competition 20-2-2016
